spring.cloud.aws:
  region.static: ap-northeast-2
---
spring:
  application.name: server

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password:

  config:
    activate.on-profile: dev
    import: aws-parameterstore:/yeohaeng-ttukttak/server_dev/


management:
  server.port: 8081

  endpoints:
    enabled-by-default: false
    web.exposure.include: health

  endpoint:
    health.enabled: true

oauth:
  google:
    client-id: 951324022006-eigc5h6tj71rm2v31eqr5u0v07cbmpn1.apps.googleusercontent.com
    client-secret: ${GoogleOAuthProperties}
    scope: https://www.googleapis.com/auth/user.gender.read https://www.googleapis.com/auth/user.birthday.read
    redirect-uri: https://dev.yeohaeng-ttukttak.com/api/v2/users/sign-up
    grant-type: authorization_code
